/**
 * Represents an individual historical sample point in the 
 * moving time-series graph rendered on the UI client side.
 */
export interface MetricSnapshot {
  time: string; // Formatted local timestamp (e.g., "12:05:00")
  cpu: number;  // CPU Utilization percentage
  mem: number;  // Memory Utilization percentage
}

/**
 * Strict structural contract representing the exact active data structure
 * sent by your Java Agent into the 'server_states' Firestore collection.
 */
export interface ServerState {
  // --- Infrastructure Identity Layer ---
  osName: string;       // e.g., "Windows Server 2022", "Red Hat Enterprise Linux", "AIX LPAR"
  osVersion: string;    // Raw OS version kernel string
  architecture: string; // x86_64, ppc64, etc.
  timestamp: number;    // Epoch milliseconds timestamp from the Java runtime

  // --- Core Performance Utilization Metrics ---
  cpuUtilizationPercent: number;    // Real-time calculated overall CPU load
  memoryUtilizationPercent: number; // Real-time calculated overall RAM load

  // --- Detailed Hardware Footprint Breakdown ---
  totalMemoryBytes?: number;     // Total physical RAM installed on the host
  availableMemoryBytes?: number; // Total unused RAM available on the subsystem
  systemUptimeSeconds?: number;  // Host system uptime tracking counter
  
  // --- UI-Exclusive State (Local Buffer Engine) ---
  // This property is appended locally by our React state listener hook to manage 
  // the moving time-series history loop without increasing Firestore storage bills.
  history?: MetricSnapshot[];
}

/**
 * Valid strict definitions for our custom infrastructure threat prioritization alerts.
 */
export type AlertPriority = 'HIGH' | 'LOW' | 'IGNORABLE';

/**
 * Strict structural contract representing an operational breach log entry 
 * stored within the 'peak_logs' Firestore collection.
 */
export interface PeakLog {
  id: string;               // Document identifier generated by Firestore
  serverId: string;         // Host node that experienced the resource constraint
  timestamp: number;        // Exact moment the resource breached threshold configurations
  priority: AlertPriority;  // Severity weighting: HIGH, LOW, or IGNORABLE
  resource: 'CPU' | 'MEMORY'; // Target hardware subsystem that peaked
  peakValuePercent: number; // The maximum value recorded during the breach
  status: 'UNRESOLVED' | 'RESOLVED'; // Operational lifecycle flag for dashboard management
  
  // Captures a frozen copy of the complete system metrics state at the exact second 
  // the peak anomaly hit, allowing admins to inspect full logs retrospectively.
  snapshotMetrics?: Omit<ServerState, 'history'>; 
}